### ISSUE TITLE
Map home/away buttons to set hold for named climates for non-EMS thermostats

### ISSUE THREAD

**Issue by watou** [watou/vera-ecobee#13]
The home/away buttons currently work by offsetting the current setpoints by the Quick Save relative values.  On the ecobee3 (aka athenaSi model name), the user does not appear to have access in the new web UI to control these values.  Also, the ecobee3 has presence detection and may switch to away mode on its own.  There is now a strong argument to have the plugin's "away" mode simply set an indefinite hold to the "away" named climate, and the "home" mode set an indefinite hold to the "home" named climate (where "climate" is the API name for "comfort setting").  Preserve the old behavior (maybe?) for the older models.

**Comment by tomgru1** [comment]
Love this idea!  Keeps it simple and easy to understand!

**Comment by watou** [comment]
Another way of saying what this change will be: Change the home/away button so it sets an indefinite hold for the either the "home" or "away" climate/comfort setting, and the Vera device reports "1" if the current climate/comfort setting is "home", and "0" in all other cases (like "away", "sleep" or any other climate/comfort setting).  This will undo the existing behavior where "away" uses the quickSave setback and setforward offsets of the current setpoints, thereby giving users more control and consistency.
