### ISSUE TITLE
Version 1.6: options greyed out when creating scene. Can't control fan.

### ISSUE THREAD

**Issue by kevinkey619b** [watou/vera-ecobee#29]
Hi,

I just installed version 1.6. I'm not able to control anything when I create a scene: all options are greyed out. Also, I see no way to control the fan (auto/continuous). I have the latest Vera and Ecobee firmware. Do I need to do a factory reset on my Vera and Ecobee?

**Comment by watou** [comment]
As this issue does not seem to be related to the plugin itself, I will close it.
