### ISSUE TITLE
Scenes no longer supported?

### ISSUE THREAD

**Issue by kevinkey619** [watou/vera-ecobee#30]
I just got done doing factory resets of my Vera Lite and my Ecobee thermostat. Still, when I try to create a scene all the options are greyed out and cannot be validated. Also there is no fan control when creating a scene.  Does this plug in only support manual control via "Devices"?  I can't recall how many times I've generated new PINs to no avail.

**Comment by kevinkey619** [comment]
Meanwhile I'm trying to downgrade the firmware of my VeraLite to 1.5.622 in an effort to make this plugin work...

**Comment by watou** [comment]
If you generate a new PIN, register it at ecobee.com, and wait around 3 or more minutes, the plugin should register with the API and retrieve device variables and allow changes.  There are a number of triggers defined that ought to be usable in scenes.  Please be certain you want to downgrade your firmware, as some accounts of UI7 are positive and there may be unwanted side effects from downgrading.  Please consider continuing on the Vera forum so others' experience could be compared.

**Comment by kevinkey619** [comment]
I've tried generating a new PIN numerous times. I'm still trying to downgrade my firmware to 1.5.622, but keep running into issues. It seems that this plugin is incompatible with U17?

**Comment by kevinkey619** [comment]
The Vera forum is worthless in this regard.

**Comment by kevinkey619** [comment]
Downgrade to 1.5.622 continues to fail. I wish I had known that this plugin wasn't compatible with later versions of firmware ahead of time.

**Comment by kevinkey619** [comment]
Now trying to install an earlier version of the plugin, but no luck:  

http://192.168.1.7/:3480/data_request?id=action&serviceId=urn:micasaverde-com:serviceId:HomeAutomationGateway1&action=CreatePlugin&PluginNum=3586&Version=1.3

http://192.168.1.7/:3480/data_request?id=action&serviceId=urn:micasaverde-com:serviceId:HomeAutomationGateway1&action=CreatePlugin&PluginNum=3586&Version=13

**Comment by kevinkey619** [comment]
Well, after MUCH frustration, I discovered a workaround:

The free beta VeraMobile app for Windows 10 lets me successfully create an event with the Ecobee plugin! And I can still keep the latest UI otherwise.

Kevin

**Comment by watou** [comment]
Glad you found a workaround.
