### ISSUE TITLE
TLS 1.0 no longer supported

### ISSUE THREAD

**Issue by watou** [watou/vera-ecobee#42]
Observations suggest that the plugin was only connecting with TLS 1.0, but now it requires TLS 1.2.

**Comment by Lee1135** [comment]
so is the new version 1.9 pushed to the MiOS marketplace? The ecobee plugin is still 1.8 in my UI5, even though it's set as "auto update", or do I need to install manually?

**Comment by watou** [comment]
@Lee1135 I vaguely remember some of my plugins on UI5 seemed like they should have updated but needed prodding.  The 1.9 was uploaded and worked for at least UI7 users.  I got a report that seemed to suggest that UI5 does not have support for tlsv1_2, which if true would mean that UI5 can no longer be used to talk to Ecobee.  But I never saw any proof certain of this, and it's been years since I used my Veras.  All the best!

**Comment by watou** [comment]
Closing since 1.9 has been reported to correct the change at api.ecobee.com.

**Comment by everettcaz** [comment]
I have updated my plugin to 1.9 and "GET PIN" still yields no code

**Comment by watou** [comment]
@everettcaz There might be a problem if you are on the old UI5, but since I have no ability to help directly, please consider visiting [this site](http://forum.micasaverde.com/index.php/topic,13836.msg429038.html#msg429038) hoping others can help you.
