### ISSUE TITLE
Using LUUP to turn furnace OFF

### ISSUE THREAD

**Issue by hmspain** [watou/vera-ecobee#43]
Please consider this a hail mary for help.  I'm trying to use your old Ecobee code to turn OFF my furnace.  I turn off my furnace/air conditioner when my whole house fan runs :-).

Here is the code that I think should work:

local service_id = "urn:upnp-org:serviceId:HVAC_UserOperatingMode1"
local action = "SetMode"
local args = {NewMode="Off"}
local dev_num = 1507
luup.call_action(service_id, action, args, dev_num)

Can you see anything wrong with the code?  I pasted this in the app developer window and it executes, but my Ecobee remains in "Heat" mode :-).

Many thanks if you can see anything, and I'll certainly understand if you choose not to respond.

Harrison Spain

**Comment by watou** [comment]
I see this code in the old plugin and it looks like you need to use `SetModeTarget` and `NewModeTarget` (i.e., you're missing Target in a couple places)?

```
    <action>
      <serviceId>urn:upnp-org:serviceId:HVAC_UserOperatingMode1</serviceId>
      <name>SetModeTarget</name>
      <run>
        -- tell the ecobee to switch to lul_settings.NewModeTarget
        local hvacMode = upnpToEcobee(HVAC_USER_SID, "SetModeTarget", "NewModeTarget", lul_settings)
        local session = loadSession()
        local selection = getSelection(session, lul_device) 
        if hvacMode and updateThermostats(session, ecobee.thermostatsUpdateOptions(selection, nil, 
                                                         { settings = { hvacMode = hvacMode } })) then
          writeVariableIfChanged(lul_device, HVAC_USER_SID, "ModeTarget", lul_settings.NewModeTarget)
          getStatusSoon()
        else
          task("Failed to set new hvacMode to " .. tostring(hvacMode))
        end
      </run>
    </action>
```

**Comment by hmspain** [comment]
Thank you John!  I'll try this right away!

Harrison

**Comment by hmspain** [comment]
Worked perfectly, thank you again!!!! :-)

Harrison
